stages:
- cmake

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  - make clean
  - make
  - echo 'Make Finished'
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTest
  - ./MagnetTest
  - ./MagnetFactoryTest
  - ./EPICSInterfaceTest
  - ./EPICSMagnetInterfaceTest  
  - ./BPMTest
  - ./EPICSBPMInterfaceTest
  - ./BPMFactoryTest
  - scp ./Documentation/html/* ujo48515@148.79.232.81:/var/www/html/
