stages:
- cmake

before_script:
  - which gcc
  - which g++
  - which python3
  - echo $PATH
  - ls

cmake_build:
  stage: cmake
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  - make clean
  - make
  - echo 'Make Finished'
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests

doxygen: 
  stage: doxygen
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - cd build
  - doxygen Doxyfile.CATAPDocs
  - scp -r ./Documentation/html/* ujo48515@172.16.114.88:/var/www/html/
  only:
   - master


