stages:
- cmake
- make
- tests
- doxygen
- sphinx

before_script:
  - which gcc
  - which g++
  - which python3
  - echo $PATH
  - ls

cmake:
  stage: cmake
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls

make:
  stage: make
  cache:
     key: ${CI_COMMIT_SHORT_SHA}
     paths:
       - build/*  
  script:
  - cd build/
  - make clean
  - make
  - echo 'Make Finished'

tests:
  stage: tests
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths: 
      - build/*
  script:
  - cd build  
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests

doxygen: 
  stage: doxygen
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - cd build
  - doxygen ./Docs/cppdocs/Doxyfile.CATAPDocs
  - scp -r ./Docs/cppdocs/html* ujo48515@172.16.114.88:/var/www/html/CATAPcpp
  only:
    - master

sphinx:
  stage: sphinx
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - cd build
  - scp -r ./Docs/pydocs/html/* ujo48515@172.16.114.88:/var/www/html/CATAPpy
  only:
    - master

