stages:
- cmake
- make
- tests
- doxygen
before_script:
  - which gcc
  - which g++
  - which python3
  - echo $PATH

cmake:
  stage: cmake
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  cache:
    key: cmake-cache
    paths:
    - build/
make:
  stage: make  
  script:
  - make clean
  - make
  - echo 'Make Finished'
  cache:
     key: make-cache
     paths:
     - build/
tests:
  stage: tests
  script:  
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests
  cache:
    key: make-cache
doxygen: 
  stage: doxygen
  cache:
    key: make-cache
  script: 
  - cd ../
  - doxygen Doxyfile.CATAPDocs
  - scp -r ./Documentation/html/* ujo48515@172.16.114.88:/var/www/html/
  only:
  - merge_requests

