stages:
- cmake
- make

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  script:
  - cmake .
  - echo 'CMake Finished'
  artifacts: 
    paths:
      - build/
make_build:
  stage: make
  dependencies:
    - cmake_build
  script:
    - make .
    

