stages:
- cmake
- make
- tests
- doxygen

before_script:
  - which gcc
  - which g++
  - which python3
  - echo $PATH

build_test_document:
  stage: cmake
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  stage: make
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - cd build/
  - make clean
  - make
  - echo 'Make Finished'
  stage: tests
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - cd build  
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests
  stage: doxygen
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - doxygen Doxyfile.CATAPDocs
  - scp -r ./Documentation/html/* ujo48515@172.16.114.88:/var/www/html/
  only:
  - merge_requests

merging:
  stage: cmake
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  only:
  - merge_requests
  stage: make
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - cd build/
  - make clean
  - make
  - echo 'Make Finished'
  only:
  - merge_requests
  stage: tests
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - cd build  
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests
  only:
  - merge_requests  
  stage: doxygen
  cache: 
    key: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - build/*
  script:
  - doxygen Doxyfile.CATAPDocs
  - scp -r ./Documentation/html/* ujo48515@172.16.114.88:/var/www/html/
  only:
  - merge_requests
