stages:
- cmake_linux
- make_linux
- tests_linux
- doxygen_linux
- sphinx_linux
- wheel_linux

before_script:
  - which gcc
  - which g++
  - which python3
  - echo $PATH
#  - echo EPICS_CA_ADDR_LIST $EPICS_CA_ADDR_LIST
#  - echo EPICS_CA_AUTO_ADDR_LIST $EPICS_CA_AUTO_ADDR_LIST
#  - echo EPICS_CA_SERVER_PORT $EPICS_CA_SERVER_PORT
  - ls

cmake_linux:
  stage: cmake_linux
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  tags: ["linux"]

make_linux:
  stage: make_linux
  cache:
     key: ${CI_COMMIT_SHORT_SHA}
     paths:
       - build/*  
  script:
  - cd build/
  - make clean
  - make
  - echo 'Make Finished'
  tags: ["linux"]

tests_linux:
  stage: tests_linux
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths: 
      - build/*
  script:
#  - /bin/bash ~/start_vm.script
  - cd build  
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests
  - ./EPICSToolsTests
  tags: ["linux"]
  

doxygen_linux:
  stage: doxygen_linux
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - cd build
  - doxygen ./Docs/cppdocs/Doxyfile.CATAPDocs
  - scp -r ./Docs/cppdocs/html/* ujo48515@172.16.114.88:/var/www/html/CATAPcpp
  only:
    - master
  tags: ["linux"]
   
sphinx_linux:
  stage: sphinx_linux
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - cd build
  - scp -r ./Docs/pydocs/html/* ujo48515@172.16.114.88:/var/www/html/CATAPpy
  only:
    - master
  tags: ["linux"]

wheel_linux:
  stage: wheel_linux
  cache:
    key: ${CI_COMMIT_SHORT_SHA}
    paths:
      - build/*
  script:
  - cd build
  - cd ./PythonInterface/CATAP/
  - ./build_wheel.sh
  only:
    - master
  tags: ["linux"]
