stages:
- cmake
- test


cache:
  key: $CI_JOB_ID 
  paths:
    - build

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  - make
  - echo 'Make Finished'
test_build:
  stage: test
  dependencies:
    - cmake_build
  script:
    - cd build/testBin
    - ls
    

