stages:
- cmake
- test

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  cache:
    key: $CI_COMMIT_REF_NAME 
    paths:
      - build
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls
  - make
  - echo 'Make Finished'
test_build:
  stage: test
  dependencies:
    - cmake_build
  script:
    - cd build/testBin
    - ls
    

