stages: 
  - cmake
  - make
  - tests
  - doxygen
  - sphinx
  - wheel

cmake_linux: 
  cache: 
    key: "${CI_COMMIT_SHORT_SHA}"
    paths: 
      - build/*
  script: 
    - "mkdir build"
    - "cd build"
    - "cmake ../."
    - "echo 'CMake Finished'"
    - ls
  stage: cmake
  tags: 
    - linux

cmake_windows: 
  cache: 
    key: ${CI_COMMIT_SHORT_SHA}
    paths: 
      - build/*
  script: 
    - "mkdir build"
    - "cd build"
    - "cmake ../. ."
    - dir
  stage: cmake
  tags: 
    - windows


linux_make: 
  cache: 
    key: "${CI_COMMIT_SHORT_SHA}"
    paths: 
      - build/*
  script: 
    - cd build/
    - make clean
    - make
    - echo 'Make Finished'
  stage: make
  tags: 
    - linux
ms_build: 
  cache: 
    key: ${CI_COMMIT_SHORT_SHA}
    paths: 
      - build/*
  script: 
    - cd build
    - "MSBuild.exe ALL_BUILD.vcxproj /property:Configuration=Release"
  stage: make
  tags: 
    - windows

linux_tests: 
  cache: 
    key: "${CI_COMMIT_SHORT_SHA}"
    paths: 
      - build/*
  script: 
    - cd build
    - cd testBin
    - echo 'Running Tests..'
    - ls ~/MasterLattice
    - ./ConfigReaderTest
    - ./LoggingSystemTest
    - ./HardwareTests
    - ./FactoryTests
    - ./EPICSInterfaceTests
    - ./EPICSToolsTests
  stage: tests
  tags:
    - linux

windows_tests: 
  cache: 
    key: ${CI_COMMIT_SHORT_SHA}
    paths: 
      - build/*
  script: 
    - cd build
    - cd testBin
    - cd Release
    - dir
    - .\ConfigReaderTest.exe
    - .\LoggingSystemTest.exe
    - .\HardwareTests.exe
    - .\FactoryTests.exe
    - .\EPICSInterfaceTests.exe
    - .\EPICSToolsTests.exe
  stage: tests
  tags:
    - windows

doxygen: 
  cache: 
    key: "${CI_COMMIT_SHORT_SHA}"
    paths: 
      - build/*
  only: 
    - master
  script: 
    - "cd build"
    - "doxygen ./Docs/cppdocs/Doxyfile.CATAPDocs"
    - "scp -r ./Docs/cppdocs/html/* ujo48515@172.16.114.88:/var/www/html/CATAPcpp"
  stage: doxygen
  tags:
    - linux

sphinx: 
  cache: 
    key: "${CI_COMMIT_SHORT_SHA}"
    paths: 
      - build/*
  only: 
    - master
  script: 
    - "cd build"
    - "scp -r ./Docs/pydocs/html/* ujo48515@172.16.114.88:/var/www/html/CATAPpy"
  stage: sphinx
  tags:
    - linux

wheel: 
  cache: 
    key: "${CI_COMMIT_SHORT_SHA}"
    paths: 
      - build/*
  only: 
    - master
  script: 
    - "cd build"
    - "cd ./PythonInterface/CATAP/"
    - ./build_wheel.sh
  stage: wheel
  tags:
    - linux
