stages:
- cmake
- make

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  script:
    - cmake .
  cache:
    key: build-path
    paths:
    - catapillar/

make_build:
  stage: make
  script: make .
  cache:
    key: build_path
