stages:
- cmake
- test

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  script:
  - mkdir build
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - make .
  - echo 'Make Finished'
  cache:
    key: build-cache
    paths:
      - build
test_build:
  stage: test
  dependencies:
    - cmake_build
  script:
    - cd build/testBin
    - ls
    

