stages:
- cmake
- make
- tests
- doxygen

before_script:
  - which gcc
  - which g++
  - which python3
  - echo $PATH

cmake:
  stage: cmake
  cache: 
    key: cmake
    paths:
      - build/*
  script:
  - cd build
  - cmake ../.
  - echo 'CMake Finished'
  - ls

make:
  stage: make
  cache: 
    key: make
    paths:
      - build/*
  script:
  - cd build
  - make clean
  - make
  - echo 'Make Finished'

tests:
  stage: tests
  cache: 
    key: make
  script:
  - cd build  
  - cd testBin
  - echo 'Running Tests..'
  - ls ~/MasterLattice
  - ./ConfigReaderTest
  - ./LoggingSystemTest
  - ./HardwareTests
  - ./FactoryTests
  - ./EPICSInterfaceTests

doxygen: 
  stage: doxygen
  cache: 
    key: make
  script:
  - cd ../
  - doxygen Doxyfile.CATAPDocs
  - scp -r ./Documentation/html/* ujo48515@172.16.114.88:/var/www/html/
  only:
  - merge_requests

