stages:
- cmake
- test

before_script:
  - which gcc
  - which g++
  - which python3

cmake_build:
  stage: cmake
  script:
  - cmake .
  - make .
  - echo 'CMake Finished'
  cache:
    key: build-cache
    paths:
      - LoggingSystem/test/testBin/
      - ConfigReader/test/testBin/
      - Hardware/test/testBin/
      - HardwareFactory/test/testBin/
      - Magnet/test/testBin/
      - EPICSInterace/test/testBin/
      - PythonInterface/test/testBin/
test_build:
  stage: test
  dependencies:
    - cmake_build
  script:
    - cd LoggingSystem/test/testBin
    - ./LoggingSystemTest
    

